# Generated by Django 5.0 on 2024-03-04 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to='', verbose_name='file in storage')),
                ('filename', models.CharField(default='', max_length=255, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('size', models.CharField(default='', null=True)),
                ('share_link', models.CharField(default='', max_length=100, null=True)),
                ('upload_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('by_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
